# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b78cb700811afda30819bd6447e6855e1139928072400d9e8aa4b4f1599ac06bd4f7dd7f855253fb0197aea8d2c7885a64deb5b79cd918ac5667ad363874ebc9

test:
  secret_key_base: e88e50289caf997e6f91c762f4019c7ce227a6af11e4a52dc8e53d9ba81e2584013f37fd5e5cffa77ebdfa006063dd874e8f4443fe54d0fed2b2ec6f84a515f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
